[global]
    workgroup = CORPAMAG
    server string = Servidor Archivos CORPAMAG
    security = user
    map to guest = bad user
    log file = /var/log/samba/%m.log
    max log size = 50

[documentos]
    path = /srv/samba/documentos
    browseable = yes
    writable = yes
    guest ok = yes
    create mask = 0664
    directory mask = 0775
    comment = Documentos internos CORPAMAG
